Create a Location Hierarchy API
opensrp/hapi-fhir-opensrp-extensions pull request #1
Opened 2021-08-24 07:49 UTC by rehammuzzamil

https://github.com/opensrp/fhircore/issues/188

2021-08-24 17:16 UTC, pld reviewed
can we write test for this?

2021-08-24 20:09 UTC, rehammuzzamil commented
> can we write test for this?

Sure, will add unit tests for this repo.

2021-08-25 23:18 UTC, pld approved these changes
lgtm!

2021-08-26 14:59 UTC, pld approved these changes

2021-08-27 08:09 UTC, dubdabasoduba requested changes

2021-08-27 08:09 UTC, dubdabasoduba commented on pom.xml
> +
Please add the publishing settings


```
<distributionManagement>
		<snapshotRepository>
			<id>nexus-snapshots</id>
			<name>Nexus Snapshots Repository</name>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
			<uniqueVersion>false</uniqueVersion>
		</snapshotRepository>
		<repository>
			<id>nexus-releases</id>
			<url>https://oss.sonatype.org/service/local/staging/deploy/maven2</url>
		</repository>
	</distributionManagement>
```

2021-08-27 08:09 UTC, dubdabasoduba commented on src/main/java/org/smartregister/extension/model/LocationHierarchy.java
> +		Location dst = new Location();
Use a better name other that `dst`

2021-08-27 08:09 UTC, dubdabasoduba commented on src/main/java/org/smartregister/extension/model/LocationHierarchy.java
> +		List<Bundle.BundleEntryComponent> theEntry = new ArrayList<>();
Please name the variables according to what the hold or do

2021-08-27 08:09 UTC, dubdabasoduba commented on src/main/java/org/smartregister/extension/model/Tree.java
> +		if (idString.contains("/_")) {
Move this to a constants file

2021-08-27 08:09 UTC, dubdabasoduba commented on src/main/java/org/smartregister/extension/model/Tree.java
> +			idString = idString.substring(0, idString.indexOf("/_"));
Move this to a constants file

2021-08-27 08:09 UTC, dubdabasoduba commented on src/main/java/org/smartregister/extension/model/Tree.java
> +			if (parentChildren.get(i) != null && parentChildren.get(i).getIdentifier() != null
When checking Strings use `StringUtils.isNotBlank`

2021-08-27 08:09 UTC, dubdabasoduba commented on src/main/java/org/smartregister/extension/model/Tree.java
> +		TreeNode n = makeNode(id, label, node, parentId);
Rename this to a better variable name

2021-08-27 08:09 UTC, dubdabasoduba commented on src/main/java/org/smartregister/extension/model/Tree.java
> +			TreeNode p = getNode(parentId);
Rename to a better variable name

2021-08-27 08:09 UTC, dubdabasoduba commented on src/main/java/org/smartregister/extension/model/Tree.java
> +				if (idString.contains("/_")) {
Move the `"/_"` to constants

2021-08-27 08:09 UTC, dubdabasoduba commented on src/main/java/org/smartregister/extension/model/Tree.java
> +					idString = idString.substring(0, idString.indexOf("/_"));
Move the `"/_"` to constants

2021-08-27 08:09 UTC, dubdabasoduba commented on src/main/java/org/smartregister/extension/model/Tree.java
> +				idString = idString.substring(0, idString.indexOf("/_"));
Move the `"/_"` to constants

2021-08-27 08:09 UTC, dubdabasoduba commented on src/main/java/org/smartregister/extension/model/Tree.java
> +		TreeNode n = getNode(id);
Rename the variables

2021-08-27 08:09 UTC, dubdabasoduba commented on src/main/java/org/smartregister/extension/rest/LocationHierarchyResourceProvider.java
> +		partOf.setValue("Location/" + id);
Please move all hardcoded strings to a constants file

2021-08-27 08:41 UTC, rehammuzzamil commented on pom.xml
> +
Added

2021-08-27 08:41 UTC, rehammuzzamil commented on src/main/java/org/smartregister/extension/model/LocationHierarchy.java
> +		Location dst = new Location();
Done

2021-08-27 08:42 UTC, rehammuzzamil commented on src/main/java/org/smartregister/extension/model/Tree.java
> +		if (idString.contains("/_")) {
Created constants file.

2021-08-27 08:57 UTC, rehammuzzamil commented on src/main/java/org/smartregister/extension/model/Tree.java
> +		TreeNode n = getNode(id);
Done

2021-08-27 08:58 UTC, rehammuzzamil commented on src/main/java/org/smartregister/extension/model/Tree.java
> +			if (parentChildren.get(i) != null && parentChildren.get(i).getIdentifier() != null
Done

2021-08-27 08:58 UTC, rehammuzzamil commented on src/main/java/org/smartregister/extension/model/Tree.java
> +		TreeNode n = makeNode(id, label, node, parentId);
Done

2021-08-27 08:58 UTC, rehammuzzamil commented on src/main/java/org/smartregister/extension/model/Tree.java
> +			TreeNode p = getNode(parentId);
Done

2021-08-31 08:58 UTC, dubdabasoduba approved these changes

2021-08-31 09:00 UTC, merged